services:
  neardrop:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: neardrop

    restart: unless-stopped

    ports:
      - '3000:3000'

    volumes:
      - ./uploads:/app/uploads
